
const Homeproduct =
[
    {
        id: 1,
        Name: 'Winter Jacket',
        price: '2600',
        image: 'image/jack-2.png',
        cat: 'clothing',
        type: 'new',
    },
    {
        id: 2,
        Name: 'Check Shirt',
        price: '1450',
        image: 'image/shirt-1.jpg',
        cat: 'clothing',
        type: 'new',
    },
    {
        id: 3,
        Name: 'Blazer',
        price: '7800',
        image: 'image/blazer-2.png',
        cat: 'clothing',
        type: 'new',
    },
    {
        id: 4,
        Name: 'Women heels',
        price: '2380',
        image: 'image/f-shoes-2.jpg',
        cat: 'shoes',
        type: 'new',
    },
    {
        id: 5,
        Name: 'Footwear shoes',
        price: '2100',
        image: 'image/f-shoes-1.jpg',
        cat: 'shoes',
        type: 'featured',
    },
    {
        id: 6,
        Name: 'formal shoes',
        price: '4500',
        image: 'image/m-shoes-3.jpg',
        cat: 'shoes',
        type: 'featured',
    },
    {
        id: 7,
        Name: 'Boy kid jeans',
        price: '1290',
        image: 'image/k-3.jpg',
        cat: 'kids',
        type: 'featured',
    },
    {
        id: 8,
        Name: 'Girls kid jeans',
        price: '1300',
        image: 'image/k-2.jpg',
        cat: 'kids',
        type: 'featured',
    },
    {
        id: 9,
        Name: 'Kids full-set',
        price: '3299',
        image: 'image/k-1.jpg',
        cat: 'kids',
        type: 'top',
    },
    {
        id: 10,
        Name: 'Laptop',
        price: '62999',
        image: 'image/p-2.png',
        cat: 'tech',
        type: 'top',
    },
    {
        id: 11,
        Name: 'Smart watch',
        price: '9450',
        image: 'image/p3.webp',
        cat: 'tech',
        type: 'top',
    },
    {
        id: 12,
        Name: 'Smaert phone',
        price: '29500',
        image: 'image/p6.webp',
        cat: 'tech',
        type: 'top',
    },
    {
        id: 13,
        Name: 'Composition cosmetics',
        price: '5999',
        image: 'image/c-1.png',
        cat: 'cosm',
        type: 'top',
    },
    {
        id: 14,
        Name: 'Various cosmetics',
        price: '3450',
        image: 'image/c-3.jpg',
        cat: 'cosm',
        type: 'top',
    },
    {
        id: 15,
        Name: 'Brush isolated',
        price: '1450',
        image: 'image/c-3.jpg',
        cat: 'cosm',
        type: 'top',
    },
    {
        id: 16,
        Name: 'Couple sportswear',
        price: '3100',
        image: 'image/a-2.png',
        cat: 'sports',
        type: 'top',
    },
    {
        id: 17,
        Name: 'Various cosmetics',
        price: '3450',
        image: 'image/a-1.png',
        cat: 'sports',
        type: 'top',
    },
    {
        id: 18,
        Name: 'Brush isolated',
        price: '1450',
        image: 'image/a-3.png',
        cat: 'sports',
        type: 'top',
    },
]
export default Homeproduct